#!/usr/bin/env bash
case "$1" in
  start)
    sudo systemctl start openvpn-kmitl
    # Wait for tun0 to appear (timeout 10s)
    for i in {1..10}; do
      if ip link show tun0 &>/dev/null; then
        break
      fi
      sleep 1
    done
    sudo resolvectl dns tun0 10.30.32.1
    sudo resolvectl domain tun0 '~.'
    ;;
  stop)
    sudo systemctl stop openvpn-kmitl && \
    sudo resolvectl revert tun0
    ;;
  status)
    sudo systemctl status openvpn-kmitl
    ;;
  *)
    echo "Usage: it-kmitl {start|stop|status}"
    ;;
esac