#!/usr/bin/env bash
case "$1" in
  start)
    sudo systemctl start openvpn-kmitl
    ;;
  stop)
    sudo systemctl stop openvpn-kmitl
    ;;
  status)
    sudo systemctl status openvpn-kmitl
    ;;
  *)
    echo "Usage: it-kmitl {start|stop|status}"
    ;;
esac