#!/usr/bin/env bash
case "$1" in
  start)
    sudo systemctl start openvpn-kmitl && \
    if [ ! -f /etc/resolv.conf.bak ]; then sudo cp /etc/resolv.conf /etc/resolv.conf.bak; fi && \
    echo "nameserver 10.30.32.1" | sudo tee /etc/resolv.conf
    ;;
  stop)
    sudo systemctl stop openvpn-kmitl && \
    if [ -f /etc/resolv.conf.bak ]; then sudo mv /etc/resolv.conf.bak /etc/resolv.conf; fi
    ;;
  status)
    sudo systemctl status openvpn-kmitl
    ;;
  *)
    echo "Usage: it-kmitl {start|stop|status}"
    ;;
esac